/**
 * Vendor-neutral anatomy tool layer — shared types.
 *
 * Nothing in `src/lib/anatomy/` may import from SvelteKit (`$app/*`, `$env/*`)
 * or touch the network, so the MCP route, the embedded widget and the app can
 * all import it unchanged. See AI_PLUGIN.md §6.
 */

/** The 10 layer keys in `src/data/objects.json`. */
export type AnatomyLayer =
  | "skin"
  | "skeleton"
  | "connective"
  | "muscular"
  | "vascular"
  | "nervous"
  | "lymphatic"
  | "respiratory"
  | "digestive"
  | "urogenital";

export const ANATOMY_LAYERS: readonly AnatomyLayer[] = [
  "skin",
  "skeleton",
  "connective",
  "muscular",
  "vascular",
  "nervous",
  "lymphatic",
  "respiratory",
  "digestive",
  "urogenital",
] as const;

/**
 * Layers whose geometry sits behind a single named mesh, so a request for a
 * structure *within* them cannot be highlighted at sub-layer granularity:
 * vascular has only `heart` + `vascular_system`, nervous only `brain` +
 * `nerves`, lymphatic only `lymphatic_system`. The resolver reports these as
 * whole-system rather than silently painting 160k vertices. See AI_PLUGIN.md §2.
 */
export const WHOLE_SYSTEM_ONLY_LAYERS: readonly AnatomyLayer[] = [
  "vascular",
  "nervous",
  "lymphatic",
] as const;

export type Sex = "male" | "female";

export type Side = "left" | "right" | "bilateral" | "midline";

/** Per-sex inventory of mesh names actually present in the geometry. */
export type AnatomyManifest = Record<Sex, string[]>;

export interface AnatomyCandidate {
  id: string;
  label: string;
}

export interface AnatomyResolution {
  /** True when the input resolved to at least one known anatomical id. */
  ok: boolean;
  /** The caller's input, verbatim. */
  input: string;
  /** Region id or exact-case mesh name. Null when unresolved. */
  canonicalId: string | null;
  /** Human-readable English label. Empty string when unresolved. */
  label: string;
  /** Present only for meshes with a populated SNOMED CT code (122 of 465). */
  snomedCode?: string;
  /** Exact-case mesh names, filtered against the manifest when one is supplied. */
  meshes: string[];
  /** Resolved but absent from this sex's geometry — see AI_PLUGIN.md §2. */
  unavailable: string[];
  /** Layers the resolved meshes belong to. */
  layers: AnatomyLayer[];
  side: Side;
  /**
   * True when the target lives in a layer with no sub-layer granularity, so
   * `meshes` is the whole system rather than the requested structure.
   */
  wholeSystemOnly: boolean;
  /** Populated when `ok` is false, or when the match was ambiguous. */
  candidates: AnatomyCandidate[];
  /** Which resolver step produced the match — for tests and telemetry. */
  matchedBy:
    | "alias"
    | "exact"
    | "case-insensitive"
    | "snomed"
    | "label"
    | "clinical-alias"
    | "token-overlap"
    | null;
}

export interface ResolveOptions {
  /**
   * Region id to scope candidate matching to. Both raises accuracy and makes an
   * otherwise ambiguous term like "medial" resolvable.
   */
  within?: string;
  /** Filters `meshes` against the manifest and partitions the rest into `unavailable`. */
  sex?: Sex;
  /**
   * Real per-sex geometry inventory, generated by
   * `scripts/anatomy-pipeline/verify.mjs`. Injected rather than imported so the
   * resolver does not depend on the asset pipeline. Absent ⇒ treat every
   * declared mesh as available.
   */
  manifest?: AnatomyManifest;
}
